import { getPostBySlug, getAllPosts } from "@/lib/blog";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import BlogTOC from "@/components/BlogTOC";
import Link from "next/link";
import Image from "next/image";
import { notFound } from "next/navigation";
import type { Metadata } from "next";
import { BASE_URL } from "@/lib/constants";
import BlogTracker from "./BlogTracker";

interface Props {
  params: Promise<{ slug: string }>;
}

export async function generateStaticParams() {
  const posts = getAllPosts();
  return posts.map((post) => ({ slug: post.slug }));
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { slug } = await params;
  const post = await getPostBySlug(slug);
  if (!post) return {};
  return {
    title: post.title,
    description: post.description,
    alternates: {
      canonical: `/blog/${slug}`,
    },
    openGraph: {
      title: post.title,
      description: post.description,
      type: "article",
      publishedTime: post.date,
      authors: ["PERSONA（ペルソナ）"],
      // OG image is auto-generated by opengraph-image.tsx
    },
    twitter: {
      card: "summary_large_image",
      title: post.title,
      description: post.description,
      site: "@persona_consul",
      creator: "@persona_consul",
      // Twitter image is auto-generated by opengraph-image.tsx
    },
  };
}

const CATEGORY_COLORS: Record<string, string> = {
  キャリア: "bg-[#EBF5FF] text-blue",
  "業界トレンド": "bg-emerald-50 text-emerald-700",
  ノウハウ: "bg-amber-50 text-amber-700",
  "企業向け": "bg-purple-50 text-purple-700",
  "サービス紹介": "bg-red-50 text-[#E15454]",
};

export default async function BlogPostPage({ params }: Props) {
  const { slug } = await params;
  const post = await getPostBySlug(slug);

  if (!post) {
    notFound();
  }

  // Related posts (same category, exclude current)
  const allPosts = getAllPosts();
  const relatedPosts = allPosts
    .filter(
      (p) =>
        p.slug !== slug &&
        (post.category ? p.category === post.category : true)
    )
    .slice(0, 3);

  // BlogPosting JSON-LD
  const blogPostingJsonLd = {
    "@context": "https://schema.org",
    "@type": "BlogPosting",
    headline: post.title,
    description: post.description,
    datePublished: post.date,
    dateModified: post.date,
    ...(post.thumbnail
      ? { image: `${BASE_URL}${post.thumbnail}` }
      : {}),
    author: {
      "@type": "Organization",
      name: "PERSONA（ペルソナ）",
      url: BASE_URL,
    },
    publisher: {
      "@type": "Organization",
      name: "PERSONA（ペルソナ）",
      url: BASE_URL,
      logo: {
        "@type": "ImageObject",
        url: `${BASE_URL}/images/persona_logo_hero.png`,
      },
    },
    mainEntityOfPage: {
      "@type": "WebPage",
      "@id": `${BASE_URL}/blog/${slug}`,
    },
    keywords:
      post.keywords?.join(", ") || post.category || "フリーコンサル",
  };

  // BreadcrumbList JSON-LD
  const breadcrumbJsonLd = {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: [
      {
        "@type": "ListItem",
        position: 1,
        name: "ホーム",
        item: BASE_URL,
      },
      {
        "@type": "ListItem",
        position: 2,
        name: "ブログ",
        item: `${BASE_URL}/blog`,
      },
      {
        "@type": "ListItem",
        position: 3,
        name: post.title,
        item: `${BASE_URL}/blog/${slug}`,
      },
    ],
  };

  return (
    <>
      <Header />
      <BlogTracker slug={slug} category={post.category ?? ""} />
      <main className="pt-[72px] pb-16">
        {/* Hero section */}
        <div className="bg-gradient-to-b from-[#f0f8ff] to-white">
          <div className="max-w-[780px] mx-auto px-6 pt-8 pb-4">
            {/* Breadcrumbs */}
            <nav
              aria-label="パンくずリスト"
              className="text-[12px] text-[#999] mb-6 flex items-center gap-1.5 flex-wrap"
            >
              <Link
                href="/"
                className="hover:text-blue transition-colors"
              >
                ホーム
              </Link>
              <svg className="w-3 h-3 text-[#ccc]" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
              </svg>
              <Link
                href="/blog"
                className="hover:text-blue transition-colors"
              >
                ブログ
              </Link>
              <svg className="w-3 h-3 text-[#ccc]" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
              </svg>
              <span className="text-[#666] truncate max-w-[280px]">
                {post.title}
              </span>
            </nav>

            {/* Meta */}
            <div className="flex items-center gap-3 mb-4">
              {post.category && (
                <span
                  className={`text-[11px] font-bold px-3 py-1 rounded-full ${
                    CATEGORY_COLORS[post.category] || "bg-blue/5 text-blue"
                  }`}
                >
                  {post.category}
                </span>
              )}
              <time className="text-[12px] text-[#999]">{post.date}</time>
            </div>

            {/* Title */}
            <h1 className="text-[clamp(24px,4vw,34px)] font-black text-navy leading-[1.4] mb-6">
              {post.title}
            </h1>
          </div>
        </div>

        {/* Hero thumbnail — full bleed then constrained */}
        {post.thumbnail && (
          <div className="max-w-[780px] mx-auto px-6 mb-10">
            <div className="relative aspect-[16/9] overflow-hidden rounded-xl bg-[#f5f5f5] shadow-[0_4px_20px_rgba(0,0,0,0.08)]">
              <Image
                src={post.thumbnail}
                alt={post.title || ""}
                fill
                className="object-cover"
                sizes="(max-width: 780px) 100vw, 780px"
                priority
              />
            </div>
          </div>
        )}

        {/* Article content */}
        <article className="max-w-[780px] mx-auto px-6">
          {/* Table of Contents */}
          {post.toc && post.toc.length >= 3 && <BlogTOC items={post.toc} />}

          <div
            className="blog-content"
            dangerouslySetInnerHTML={{ __html: post.content ?? "" }}
          />

          {/* Author / CTA */}
          <div className="mt-14 p-6 sm:p-8 bg-gradient-to-r from-[#f0f8ff] to-[#f5f0ff] rounded-xl border border-blue/10">
            <div className="flex items-start gap-4">
              <div className="w-12 h-12 rounded-full bg-navy flex items-center justify-center shrink-0">
                <span className="text-white font-black text-sm">P</span>
              </div>
              <div>
                <p className="text-[13px] font-bold text-navy mb-1">
                  PERSONA（ペルソナ）
                </p>
                <p className="text-[12px] text-[#666] leading-[1.7] mb-3">
                  大手コンサルファーム出身者1,200名以上が登録するフリーコンサル案件紹介プラットフォーム。30社以上の提携エージェントの案件を集約し、AIマッチングで最適な案件をご紹介します。
                </p>
                <div className="flex flex-wrap gap-2">
                  <Link
                    href="/auth/register"
                    className="inline-flex items-center text-[12px] font-bold text-white bg-blue px-4 py-2 rounded-lg hover:bg-blue-dark transition-colors"
                  >
                    無料登録する
                  </Link>
                  <Link
                    href="/cases"
                    className="inline-flex items-center text-[12px] font-bold text-blue bg-white px-4 py-2 rounded-lg border border-blue/20 hover:bg-blue/5 transition-colors"
                  >
                    案件を見る
                  </Link>
                </div>
              </div>
            </div>
          </div>

          {/* Related content */}
          <aside className="mt-14">
            {relatedPosts.length > 0 && (
              <>
                <div className="flex items-center gap-3 mb-6">
                  <div className="w-1 h-6 bg-blue rounded-full" />
                  <h2 className="text-lg font-black text-navy">関連記事</h2>
                </div>
                <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 mb-10">
                  {relatedPosts.map((rp) => (
                    <Link
                      key={rp.slug}
                      href={`/blog/${rp.slug}`}
                      className="group block bg-white rounded-xl border border-border overflow-hidden transition-all hover:shadow-[0_4px_16px_rgba(0,0,0,0.06)] hover:-translate-y-0.5"
                    >
                      {rp.thumbnail && (
                        <div className="relative aspect-[16/9] overflow-hidden bg-[#f5f5f5]">
                          <Image
                            src={rp.thumbnail}
                            alt={rp.title || ""}
                            fill
                            className="object-cover transition-transform duration-500 group-hover:scale-105"
                            sizes="(max-width: 640px) 100vw, 250px"
                          />
                        </div>
                      )}
                      <div className="p-4">
                        <time className="text-[10px] text-[#aaa] block mb-1.5">
                          {rp.date}
                        </time>
                        <p className="text-[13px] font-bold text-navy leading-[1.55] line-clamp-2 group-hover:text-blue transition-colors">
                          {rp.title}
                        </p>
                      </div>
                    </Link>
                  ))}
                </div>
              </>
            )}

            {/* Cross-links */}
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <Link
                href="/cases"
                className="group block p-5 bg-white rounded-xl border border-border hover:border-blue/20 hover:shadow-[0_4px_16px_rgba(0,0,0,0.06)] transition-all"
              >
                <p className="text-[10px] font-bold text-blue tracking-[0.12em] uppercase mb-1">
                  CASES
                </p>
                <p className="text-[14px] font-bold text-navy group-hover:text-blue transition-colors">
                  フリーコンサル案件一覧を見る →
                </p>
              </Link>
              <Link
                href="/for-enterprise"
                className="group block p-5 bg-white rounded-xl border border-border hover:border-blue/20 hover:shadow-[0_4px_16px_rgba(0,0,0,0.06)] transition-all"
              >
                <p className="text-[10px] font-bold text-blue tracking-[0.12em] uppercase mb-1">
                  FOR ENTERPRISE
                </p>
                <p className="text-[14px] font-bold text-navy group-hover:text-blue transition-colors">
                  企業向けサービスを見る →
                </p>
              </Link>
            </div>
          </aside>
        </article>
      </main>
      <Footer />

      {/* Structured data */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify(blogPostingJsonLd),
        }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify(breadcrumbJsonLd),
        }}
      />
    </>
  );
}
